print("------------------------------------------")
print("               EJERCICIO 5")
print("------------------------------------------")
print ("Ingrese cantidad de docenas a comprar ")
docenas = float (input())
print ("Ingrese el valor por unidad ")
precio = float (input())
monto = precio * 12 * docenas
print("El precio cada 12 unidades es: ", monto)
print("------------------------------------------")