print("------------------------------------------")
print("               EJERCICIO 8")
print("------------------------------------------")
print("Ingrese las velocidades: ")
velocidadA =float(input ("Velocidad A: "))
velocidadB =float(input ("Velocidad B: "))
print("Ingrese la distancia que los separa: ")
distancia = float (input())
tiempo=distancia/(velocidadA+velocidadB)
print ("Los cuerpos se encontraran en ", tiempo, "segundos")
print("------------------------------------------")