console.log("-----------------------------------------------");
console.log("-----------Ejercicios de clase 3-----------");
console.log("-----------------------------------------------");
console.log("c) Crear un posteo en Facebook");
console.log ("Paso 1) Desde su computadora, abrir en el navegador la URL: www.faceook.com");
console.log ("Paso 2) Ingresar a su cuenta usando su usuario y clave, o en su defecto, registrarse");
console.log ("Paso 3) En el inicio de la pagina dirigirse al apartado 'Que estas pensando'");
console.log ("Paso 4) Escribir el posteo que desee realizar");
console.log ("Paso 5) Tocar el boton 'PUBLICAR' para subir su posteo");
console.log("-----------------------------------------------");